server:
  port: 8080
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/report_manager_db?useUnicode=true&characterEncoding=utf-8&timeZone=UTC
    username: root
    password: 123456